### ISSUE TITLE
Drop line 7

### ISSUE THREAD

**Issue by mikearango** [jfogerty18/CleanTweets#9]
https://github.com/jfogerty18/CleanTweets/blob/314f0e86e24bc3f3de3cee74f3270cb06526b0d6/CleanTweets/main.py#L7

**Comment by jfogerty18** [comment]
Hi Mike, I made the suggested changes (for both issues). I want to wait for my team mates to see the changes I made (on my branch: Jessica Branc) before I merge. Let me know if this needs to be merged right away (I'm not sure where you guys are with grading). 

thanks, 

Jessica

**Comment by mikearango** [comment]
@jfogerty18 we already graded your project, but i thought opening an issue with a comment would be a fun way to provide feedback. Feel free to submit a merge request and you can assign @htappa and @KrystinSinclair as reviewers. It'll simulate the real-world process a little more. Hope you all enjoyed the project. Great work!

**Comment by jfogerty18** [comment]
@mikearango Ok, thank you! I definitely learned a lot doing this project! 
Thanks for everything.
